In [3]:
import pandas as pd

df = pd.read_csv("../datasets/smart_farming_data.csv")
df.head()

,farm_id,region,crop_type,soil_moisture_%,soil_pH,temperature_C,rainfall_mm,humidity_%,sunlight_hours,irrigation_type,...,sowing_date,harvest_date,total_days,yield_kg_per_hectare,sensor_id,timestamp,latitude,longitude,NDVI_index,crop_disease_status
0,FARM0001,North India,Wheat,35.95,5.99,17.79,75.62,77.03,7.27,NaN,...,2024-01-08,2024-05-09,122,4408.07,SENS0001,2024-03-19,14.970941,82.997689,0.63,Mild
1,FARM0002,South USA,Soybean,19.74,7.24,30.18,89.91,61.13,5.67,Sprinkler,...,2024-02-04,2024-05-26,112,5389.98,SENS0002,2024-04-21,16.613022,70.869009,0.58,NaN
2,FARM0003,South USA,Wheat,29.32,7.16,27.37,265.43,68.87,8.23,Drip,...,2024-02-03,2024-06-26,144,2931.16,SENS0003,2024-02-28,19.503156,79.068206,0.80,Mild
3,FARM0004,Central USA,Maize,17.33,6.03,33.73,212.01,70.46,5.03,Sprinkler,...,2024-02-21,2024-07-04,134,4227.80,SENS0004,2024-05-14,31.071298,85.519998,0.44,NaN
4,FARM0005,Central USA,Cotton,19.37,5.92,33.86,269.09,55.73,7.93,NaN,...,2024-02-05,2024-05-20,105,4979.96,SENS0005,2024-04-13,16.568540,81.691720,0.84,Severe

In [4]:
df.shape

(500, 22)

In [7]:
df['crop_type'].value_counts()

crop_type
Maize      111
Soybean    108
Cotton     107
Wheat       92
Rice        82
Name: count, dtype: int64

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 22 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   farm_id               500 non-null    str
 1   region                500 non-null    str
 2   crop_type             500 non-null    str
 3   soil_moisture_%       500 non-null    float64
 4   soil_pH               500 non-null    float64
 5   temperature_C         500 non-null    float64
 6   rainfall_mm           500 non-null    float64
 7   humidity_%            500 non-null    float64
 8   sunlight_hours        500 non-null    float64
 9   irrigation_type       350 non-null    str
 10  fertilizer_type       500 non-null    str
 11  pesticide_usage_ml    500 non-null    float64
 12  sowing_date           500 non-null    str
 13  harvest_date          500 non-null    str
 14  total_days            500 non-null    int64
 15  yield_kg_per_hectare  500 non-null    float64
 16  sensor_id             500 non-null    str
 17  timestamp             500 non-null    str
 18  latitude              500 non-null    float64
 19  longitude             500 non-null    float64
 20  NDVI_index            500 non-null    float64
 21  crop_disease_status   370 non-null    str
dtypes: float64(11), int64(1), str(10)
memory usage: 86.1 KB

In [10]:
df.describe()

,soil_moisture_%,soil_pH,temperature_C,rainfall_mm,humidity_%,sunlight_hours,pesticide_usage_ml,total_days,yield_kg_per_hectare,latitude,longitude,NDVI_index
count,500.000000,500.000000,500.000000,500.000000,500.000000,500.00000,500.000000,500.000000,500.00000,500.000000,500.000000,500.000000
mean,26.750140,6.523980,24.675740,181.685740,65.194460,7.03014,26.586980,119.496000,4032.92694,22.442473,80.392248,0.602060
std,10.150053,0.585558,5.348899,72.293091,14.642849,1.69167,13.202429,16.798046,1174.43304,7.283492,5.910664,0.175402
min,10.160000,5.510000,15.000000,50.170000,40.230000,4.01000,5.050000,90.000000,2023.56000,10.004243,70.020021,0.300000
25%,17.890000,6.030000,20.295000,119.217500,51.865000,5.66750,14.945000,105.750000,2994.82000,16.263202,75.374713,0.447500
50%,25.855000,6.530000,24.655000,191.545000,65.685000,6.99500,25.980000,119.000000,4071.69000,21.981743,80.650284,0.610000
75%,36.022500,7.040000,29.090000,239.035000,77.995000,8.47000,38.005000,134.000000,5062.11000,28.528948,85.654629,0.750000
max,44.980000,7.500000,34.840000,298.960000,90.000000,10.00000,49.940000,150.000000,5998.29000,34.981531,89.991901,0.900000

In [11]:
df_clean = df.drop(columns=[
    'farm_id', 'sensor_id', 'timestamp', 'sowing_date', 'harvest_date',
    'NDVI_index', 'crop_disease_status', 'latitude', 'longitude'
])
df_clean.isnull().sum()

region                    0
crop_type                 0
soil_moisture_%           0
soil_pH                   0
temperature_C             0
rainfall_mm               0
humidity_%                0
sunlight_hours            0
irrigation_type         150
fertilizer_type           0
pesticide_usage_ml        0
total_days                0
yield_kg_per_hectare      0
dtype: int64

In [12]:
df_clean['irrigation_type'].value_counts()

irrigation_type
Sprinkler    121
Manual       118
Drip         111
Name: count, dtype: int64

In [13]:
df_clean['irrigation_type'] = df_clean['irrigation_type'].fillna('None')

In [14]:
df_clean['irrigation_type'].isnull().sum()

np.int64(0)

In [15]:
df_encoded = pd.get_dummies(df_clean, columns=['region', 'crop_type', 'irrigation_type', 'fertilizer_type'])
df_encoded.shape

(500, 26)

In [16]:
df_encoded.head()

,soil_moisture_%,soil_pH,temperature_C,rainfall_mm,humidity_%,sunlight_hours,pesticide_usage_ml,total_days,yield_kg_per_hectare,region_Central USA,...,crop_type_Rice,crop_type_Soybean,crop_type_Wheat,irrigation_type_Drip,irrigation_type_Manual,irrigation_type_None,irrigation_type_Sprinkler,fertilizer_type_Inorganic,fertilizer_type_Mixed,fertilizer_type_Organic
0,35.95,5.99,17.79,75.62,77.03,7.27,6.34,122,4408.07,False,...,False,False,True,False,False,True,False,False,False,True
1,19.74,7.24,30.18,89.91,61.13,5.67,9.60,112,5389.98,False,...,False,True,False,False,False,False,True,True,False,False
2,29.32,7.16,27.37,265.43,68.87,8.23,15.26,144,2931.16,False,...,False,False,True,True,False,False,False,False,True,False
3,17.33,6.03,33.73,212.01,70.46,5.03,25.80,134,4227.80,True,...,False,False,False,False,False,False,True,False,False,True
4,19.37,5.92,33.86,269.09,55.73,7.93,25.65,105,4979.96,True,...,False,False,False,False,False,True,False,False,True,False

In [19]:
X = df_encoded.drop(columns=['yield_kg_per_hectare'])
y = df_encoded['yield_kg_per_hectare']

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print(X_train.shape, X_test.shape)

(400, 25) (100, 25)

In [ ]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

RandomForestRegressor(random_state=42)

In [ ]:
from sklearn.metrics import mean_absolute_error, r2_score

y_pred = model.predict(X_test)

mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("MAE:", mae)
print("R²:", r2)

MAE: 1067.376918
R²: -0.08006999482778787

In [ ]:
df_encoded.corr(numeric_only=True)['yield_kg_per_hectare'].sort_values(ascending=False)

yield_kg_per_hectare         1.000000
crop_type_Soybean            0.100162
pesticide_usage_ml           0.041290
humidity_%                   0.039021
region_South India           0.036166
fertilizer_type_Inorganic    0.032712
temperature_C                0.027875
irrigation_type_Sprinkler    0.024795
soil_pH                      0.024274
sunlight_hours               0.020284
crop_type_Wheat              0.018074
irrigation_type_Manual       0.017606
region_East Africa           0.009009
fertilizer_type_Organic      0.003818
irrigation_type_Drip        -0.006134
total_days                  -0.007570
region_Central USA          -0.008930
region_North India          -0.015545
region_South USA            -0.019882
crop_type_Maize             -0.022935
irrigation_type_None        -0.033924
fertilizer_type_Mixed       -0.036524
crop_type_Cotton            -0.047731
crop_type_Rice              -0.051623
soil_moisture_%             -0.063038
rainfall_mm                 -0.076802
Name: yield_kg_per_hectare, dtype: float64

### That dataset was not sufficient had trash data that wasn't useful.

In [2]:
import pandas as pd

df2 = pd.read_csv("../datasets/yield_df.csv")
df2 = df2.drop(columns=['Unnamed: 0'])
df2.head()

,Area,Item,Year,hg/ha_yield,average_rain_fall_mm_per_year,pesticides_tonnes,avg_temp
0,Albania,Maize,1990,36613,1485.0,121.0,16.37
1,Albania,Potatoes,1990,66667,1485.0,121.0,16.37
2,Albania,"Rice, paddy",1990,23333,1485.0,121.0,16.37
3,Albania,Sorghum,1990,12500,1485.0,121.0,16.37
4,Albania,Soybeans,1990,7000,1485.0,121.0,16.37

In [3]:
df2.shape

(28242, 7)

In [4]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 28242 entries, 0 to 28241
Data columns (total 7 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Area                           28242 non-null  str
 1   Item                           28242 non-null  str
 2   Year                           28242 non-null  int64
 3   hg/ha_yield                    28242 non-null  int64
 4   average_rain_fall_mm_per_year  28242 non-null  float64
 5   pesticides_tonnes              28242 non-null  float64
 6   avg_temp                       28242 non-null  float64
dtypes: float64(3), int64(2), str(2)
memory usage: 1.5 MB

In [5]:
df2.describe()

,Year,hg/ha_yield,average_rain_fall_mm_per_year,pesticides_tonnes,avg_temp
count,28242.000000,28242.000000,28242.00000,28242.000000,28242.000000
mean,2001.544296,77053.332094,1149.05598,37076.909344,20.542627
std,7.051905,84956.612897,709.81215,59958.784665,6.312051
min,1990.000000,50.000000,51.00000,0.040000,1.300000
25%,1995.000000,19919.250000,593.00000,1702.000000,16.702500
50%,2001.000000,38295.000000,1083.00000,17529.440000,21.510000
75%,2008.000000,104676.750000,1668.00000,48687.880000,26.000000
max,2013.000000,501412.000000,3240.00000,367778.000000,30.650000

In [6]:
df2['Item'].value_counts()

Item
Potatoes                4276
Maize                   4121
Wheat                   3857
Rice, paddy             3388
Soybeans                3223
Sorghum                 3039
Sweet potatoes          2890
Cassava                 2045
Yams                     847
Plantains and others     556
Name: count, dtype: int64

In [7]:
df2['Area'].nunique()

101

In [8]:
df2[['Year', 'hg/ha_yield', 'average_rain_fall_mm_per_year', 'pesticides_tonnes', 'avg_temp']].corr()['hg/ha_yield'].sort_values(ascending=False)

hg/ha_yield                      1.000000
Year                             0.091630
pesticides_tonnes                0.064085
average_rain_fall_mm_per_year    0.000962
avg_temp                        -0.114777
Name: hg/ha_yield, dtype: float64

In [9]:
df2_encoded = pd.get_dummies(df2, columns=['Area', 'Item'])
df2_encoded.shape

(28242, 116)

In [10]:
df2_encoded.corr(numeric_only=True)['hg/ha_yield'].sort_values(ascending=False).head(15)

hg/ha_yield            1.000000
Item_Potatoes          0.610305
Item_Cassava           0.241480
Area_United Kingdom    0.174819
Item_Sweet potatoes    0.166936
Area_Japan             0.114743
Year                   0.091630
Area_Australia         0.079521
Area_New Zealand       0.077304
Area_Germany           0.076995
Item_Yams              0.076761
Area_Netherlands       0.074038
Area_Denmark           0.067903
pesticides_tonnes      0.064085
Area_Belgium           0.061025
Name: hg/ha_yield, dtype: float64

In [11]:
df2_encoded.corr(numeric_only=True)['hg/ha_yield'].sort_values(ascending=False).tail(15)

Area_Madagascar                 -0.041829
Area_Kazakhstan                 -0.041893
Area_Burkina Faso               -0.041934
Area_Iraq                       -0.043563
Area_Burundi                    -0.043580
Area_Mauritania                 -0.043954
Area_Central African Republic   -0.045118
Area_Pakistan                   -0.071321
Area_Ecuador                    -0.075415
avg_temp                        -0.114777
Item_Rice, paddy                -0.157857
Item_Maize                      -0.198230
Item_Wheat                      -0.219730
Item_Sorghum                    -0.238777
Item_Soybeans                   -0.254849
Name: hg/ha_yield, dtype: float64

In [12]:
X = df2_encoded.drop(columns=['hg/ha_yield'])
y = df2_encoded['hg/ha_yield']

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print(X_train.shape, X_test.shape)

(22593, 115) (5649, 115)

In [13]:
from sklearn.ensemble import RandomForestRegressor

model2 = RandomForestRegressor(n_estimators=100, random_state=42)
model2.fit(X_train, y_train)

RandomForestRegressor(random_state=42)

In [14]:
from sklearn.metrics import mean_absolute_error, r2_score

y_pred = model2.predict(X_test)
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("MAE:", mae)
print("R²:", r2)

MAE: 3474.4930129226414
R²: 0.9875674495149229

In [15]:
importances = pd.Series(model2.feature_importances_, index=X.columns)
importances.sort_values(ascending=False).head(15)

Item_Potatoes                    0.369278
Item_Cassava                     0.102436
Item_Sweet potatoes              0.086198
pesticides_tonnes                0.070115
Area_India                       0.058313
average_rain_fall_mm_per_year    0.044287
avg_temp                         0.041761
Year                             0.033028
Item_Yams                        0.027544
Area_United Kingdom              0.017039
Area_Japan                       0.016907
Item_Plantains and others        0.015343
Area_Canada                      0.010620
Area_Australia                   0.010325
Area_New Zealand                 0.005598
dtype: float64

In [16]:
train_data = df2_encoded[df2_encoded['Year'] <= 2009]
test_data = df2_encoded[df2_encoded['Year'] > 2009]

X_train2 = train_data.drop(columns=['hg/ha_yield'])
y_train2 = train_data['hg/ha_yield']
X_test2 = test_data.drop(columns=['hg/ha_yield'])
y_test2 = test_data['hg/ha_yield']

model3 = RandomForestRegressor(n_estimators=100, random_state=42)
model3.fit(X_train2, y_train2)

y_pred2 = model3.predict(X_test2)
print("MAE:", mean_absolute_error(y_test2, y_pred2))
print("R²:", r2_score(y_test2, y_pred2))

MAE: 10382.010527051307
R²: 0.9537629065616682

In [17]:
final_model = RandomForestRegressor(n_estimators=100, random_state=42)
final_model.fit(X, y)

RandomForestRegressor(random_state=42)

In [18]:
import joblib

joblib.dump(final_model, "../models/yield_model.pkl")

['../models/yield_model.pkl']